services:
  db_rpg:
    image: postgres:15-alpine
    container_name: meu_rpg_postgres
    environment:
      POSTGRES_USER: rpg_admin
      POSTGRES_PASSWORD: rpg_password
      POSTGRES_DB: rpg_database
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpg_admin -d rpg_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_rpg:
    build: .
    container_name: rpg_api_node
    environment:
      DB_HOST: db_rpg
      DB_PORT: 5432
      DB_NAME: rpg_database
      DB_USER: rpg_admin
      DB_PASSWORD: rpg_password
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db_rpg:
        condition: service_healthy
    volumes:
      - ./server.js:/app/server.js
      - ./database.js:/app/database.js
      - ./routes:/app/routes
    command: npm run dev

volumes:
  pgdata: